import { Fragment, useState } from "react";
import { calculateBlackJack } from "calculates";
import {
  Card,
  CardRow,
  Checking,
  Field,
  Input,
  PageTemplate,
} from "components";
import { mainBranch } from "config";

const BlackJack = () => {
  const [clientSeed, setClientSeed] = useState("");
  const [serverSeed, setServerSeed] = useState("");
  const [nonce, setNonce] = useState("");

  const [serverHash, setServerHash] = useState("");
  const [cards, setCards] = useState<
    ReturnType<typeof calculateBlackJack>["cards"]
  >({
    all: [52, 52, 52, 52],
    dealer: [52, 52],
    player: [52, 52],
  });

  const calculate = () => {
    const { cards, seed } = calculateBlackJack(clientSeed, serverSeed, nonce);

    setCards(cards);
    setServerHash(seed);
  };

  return (
    <div className={"mainWrapper"}>
      <PageTemplate>
        <ul>
          <li>
            Client Seed: This is a random hexadecimal string generated by your
            computer. The server does know about this client seed prior to the
            bet execution. Ideally, it should be freshly generated for each bet.
            However, some players have their "lucky" client seed which they
            prefer to keep.
          </li>
          <li>
            Server Seed: This is a random hexadecimal string generated by the
            server. It is not shared with the player (until they rotate the
            seed).
          </li>
          <li>
            Server Seed Hash: Since the server seed is not shared with the user,
            the server provides you with a hash of the server seed. This means
            that you can check (after the seed is rotated) whether the server
            was using the correct, shown server seed or not. The server seed
            hash is always unique and corresponds to a server seed being used to
            play games previously.
          </li>
        </ul>

        <Checking sourceLink={`https://github.com/FaucetPayio/verify/blob/${mainBranch}/src/calculates/blackjack.ts`} />

        <div className="pageContent">
          <div className="inputsRow">
            <Input
              title="Client Seed"
              subTitle="Client Seed comes from your browser and is never generated by the server."
              value={clientSeed}
              onChange={({ target }) => setClientSeed(target.value)}
            />
            <Input
              title="Server Seed"
              subTitle="Server Seed is generated by the server. It is only shared with you after you rotate the seed."
              value={serverSeed}
              onChange={({ target }) => setServerSeed(target.value)}
            />
          </div>

          <div className="inputsRow">
            <Input
              title="Nonce"
              subTitle="Nonce starts from 1 and is a count for the games you play (associated to the particular server seed)."
              value={nonce}
              onChange={({ target }) => setNonce(target.value)}
            />
            <Input
              disabled
              title="Server Seed (SHA-256)"
              subTitle="This is the SHA-256 hash of the Server Seed shown prior to rotation of the seed."
              value={serverHash}
            />
          </div>

          <button
            type="button"
            className="btn btn-info marginTop"
            onClick={calculate}>
            Calculate
          </button>

          <div className="inputsRow">
            <CardRow
              title="Dealer Cards"
              subTitle="This are the initial cards given to the dealer."
              cards={cards.dealer}
              className="blackJackCards"
            />
            <CardRow
              title="Player Cards"
              subTitle="This are the initial cards given to the player."
              cards={cards.player}
              className="blackJackCards"
            />
          </div>

          <Field
            title="Coming Cards"
            subTitle="These are the coming cards."
            className="allCardsWrapper">
            <div className="allCardsList">
              {cards.all.map((card, i) => (
                <Fragment key={`${card}_${i}`}>
                  <Card id={card} />
                </Fragment>
              ))}
            </div>
          </Field>
        </div>
      </PageTemplate>
    </div>
  );
};

export default BlackJack;
